// Ghidra headless script to decompile WFTNP-related functions from libzwiftjni.so
// Usage: analyzeHeadless <project_dir> <project_name> -import <binary> -postScript DecompileWftnp.java <output_file>
// @category Decompile

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolIterator;
import ghidra.program.model.symbol.SymbolTable;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class DecompileWftnp extends GhidraScript {

    private static final String[] FUNCTION_PATTERNS = {
        "WFTNP",
        "WahooFitnessTNP",
        "ProcessMessage",
        "SendMessage",
        "BinaryUuidToShortID",
        "HandleDiscoverServices",
        "HandleDiscoverCharacteristics",
        "WriteCharacteristic",
        "ReadCharacteristic",
        "ProcessWFTNPAdvertisedServices",
        "FTMS_Process",
        "FTMS_Control",
        "FTMS_Request",
        "FTMS_Start",
        "FTMS_Set",
        "ProcessBikeData",
        "ProcessMachineFeatures",
        "CyclingPower",
    };

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String outputPath;
        if (args.length > 0) {
            outputPath = args[0];
        } else {
            outputPath = System.getProperty("user.home") + "/wftnp_decompiled.c";
        }

        println("DecompileWftnp: Starting decompilation...");
        println("DecompileWftnp: Output path: " + outputPath);

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        List<Function> matchedFunctions = new ArrayList<>();
        SymbolTable symbolTable = currentProgram.getSymbolTable();

        // Find functions matching our patterns
        FunctionIterator funcIter = currentProgram.getFunctionManager().getFunctions(true);
        while (funcIter.hasNext()) {
            Function func = funcIter.next();
            String name = func.getName();
            for (String pattern : FUNCTION_PATTERNS) {
                if (name.contains(pattern)) {
                    matchedFunctions.add(func);
                    break;
                }
            }
        }

        println("DecompileWftnp: Found " + matchedFunctions.size() + " matching functions");

        // Sort by name for consistent output
        matchedFunctions.sort((a, b) -> a.getName().compareTo(b.getName()));

        PrintWriter out = new PrintWriter(new FileWriter(outputPath));
        out.println("// Decompiled WFTNP/FTMS functions from libzwiftjni.so");
        out.println("// Generated by Ghidra headless analyzer");
        out.println("// Binary: " + currentProgram.getExecutablePath());
        out.println("// " + new java.util.Date());
        out.println();

        int decompiled = 0;
        for (Function func : matchedFunctions) {
            println("DecompileWftnp: Decompiling " + func.getName() + " at " + func.getEntryPoint());
            DecompileResults results = decomp.decompileFunction(func, 60, monitor);
            if (results.decompileCompleted()) {
                out.println("// ============================================================");
                out.println("// Function: " + func.getName());
                out.println("// Address:  " + func.getEntryPoint());
                out.println("// ============================================================");
                out.println(results.getDecompiledFunction().getC());
                out.println();
                decompiled++;
            } else {
                out.println("// FAILED to decompile: " + func.getName());
                out.println("// Error: " + results.getErrorMessage());
                out.println();
            }
        }

        out.close();
        decomp.dispose();

        println("DecompileWftnp: Decompiled " + decompiled + "/" + matchedFunctions.size() + " functions");
        println("DecompileWftnp: Output written to " + outputPath);
    }
}
